## 5.6. Neuronal Network:

#### En primer lugar vamos a instalar Keras y Tensor Flow e importarlos:

In [1]:
import tensorflow as tf

In [2]:
pwd

u'/Users/NachoSJ/Documents/KSchool/Master DS IV/2017_09_01_SebastienP'

Prueba 1:

In [4]:
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

Hello, TensorFlow!


In [5]:
sess

Prueba 2:

In [6]:
a = tf.constant(10)
b = tf.constant(32)
print(sess.run(a + b))

42


Importamos keras:

In [147]:
from keras.models import Sequential

In [148]:
model = Sequential()

#### Stacking layers (capas) is as easy as: 

In [149]:
from keras.layers import Dense, Activation

model.add(Dense(units=64, input_dim=100))
model.add(Activation('relu'))
model.add(Dense(units=10))
model.add(Activation('softmax'))

#### Configure its learning process with

In [150]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

#### You can further configure your optimizer:

In [151]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01, momentum=0.9, nesterov=True))

NameError: name 'keras' is not defined

#### Vamos a cargar los data sets utilizados para modelizar:

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
%matplotlib inline
matplotlib.style.use("ggplot")

In [70]:
X = pd.read_csv('../Proyecto/Tenis/ETL/X')
y = pd.read_csv('../Proyecto/Tenis/ETL/y')

In [71]:
X.head()

dif_Rank  dif_RankP  dif_Height   dif_Age    w_hand    l_hand  dif_Minutes  \
0 -0.429112   0.480356    0.845264 -1.907903  0.368448 -2.576821    -0.004915   
1 -0.278954   0.634250    0.738884 -1.603764 -2.714087  0.388075    -0.004915   
2  1.356094  -0.266931    0.738884  0.043516  0.368448 -2.576821    -0.004915   
3  0.054729  -0.055915   -0.537676  0.569459  0.368448  0.388075    -0.004915   
4 -0.087086   0.036610    0.206984 -1.044215  0.368448  0.388075    -0.004915   

   dif_Aces    dif_Df  dif_1stIn  
0  1.895517 -1.833948  -0.789742  
1  1.009726  3.755639  -0.275683  
2 -0.000907 -4.543214   3.741265  
3 -0.587074 -3.116080  -1.792722  
4 -0.000907 -5.840609   0.562962

In [72]:
y.head()

Y
0  1
1  0
2  1
3  0
4  1

In [26]:
s1 = X.shape
s2 = y.shape
print s1
print s2

(42509, 10)
(42509, 1)


In [73]:
#y = y['Y']

In [106]:
#y = y.as_matrix(columns=None)

In [74]:
#X = X.as_matrix(columns=None)

In [109]:
X

array([[ -4.29111981e-01,   4.80355762e-01,   8.45264265e-01, ...,
          1.89551655e+00,  -1.83394819e+00,  -7.89741612e-01],
       [ -2.78954442e-01,   6.34250472e-01,   7.38884252e-01, ...,
          1.00972621e+00,   3.75563908e+00,  -2.75682834e-01],
       [  1.35609432e+00,  -2.66930513e-01,   7.38884252e-01, ...,
         -9.07055453e-04,  -4.54321377e+00,   3.74126547e+00],
       ..., 
       [  2.97027227e-02,  -2.86756228e+00,  -1.06957597e+00, ...,
         -7.35394181e-01,   7.80039591e-01,   2.53715762e-01],
       [ -2.03497905e-02,   2.89640829e+00,  -6.44055914e-01, ...,
         -1.02796948e+00,  -4.00832607e-01,  -7.47275503e-01],
       [  1.30185516e-02,  -1.90927297e-01,  -2.18535863e-01, ...,
         -6.19586701e-01,   2.92023009e-01,   1.34584180e+00]])

In [116]:
X.dtype

dtype('float64')

In [108]:
y

array([1, 0, 1, ..., 0, 1, 0])

In [117]:
y.dtype

dtype('int64')

#### Dividimos el modelo en set de train y set de test:

In [75]:
from sklearn.model_selection import train_test_split

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [121]:
X_train

array([[ 0.79717459, -2.45308512, -0.00577584, ..., -0.50763814,
         0.66704469, -0.0188825 ],
       [-0.32066487,  0.59978939, -0.5376759 , ..., -0.03833945,
        -0.34596061,  0.1673429 ],
       [-0.53755909,  0.51576099,  1.37716433, ...,  2.06213725,
        -0.18344832, -0.86621157],
       ..., 
       [-0.41242781,  5.49279143, -0.5376759 , ..., -0.25146284,
        -1.6066859 ,  0.94676543],
       [ 2.18196079, -0.43545938,  0.52612423, ..., -0.24748062,
        -0.30340211, -0.30855475],
       [-0.06206022,  0.12299903, -0.32491588, ...,  0.03198405,
        -0.69985844,  0.18446068]])

In [111]:
#Rows:
X_train[:,0].shape

(31881,)

In [118]:
X_train.dtype

dtype('float64')

In [112]:
#Dimensiones:
X_train[0,:].shape

(10,)

In [122]:
y_train

array([0, 1, 1, ..., 1, 1, 1])

In [113]:
len(y_train)

31881

In [119]:
y_train.dtype

dtype('int64')

#### Fit the model:

In [141]:
# x_train and y_train are Numpy arrays --just like in the Scikit-Learn API.
model.fit(X_train, y_train, epochs=5, batch_size=32)

ValueError: Error when checking input: expected dense_15_input to have shape (None, 10) but got array with shape (318810, 1)

He probado a meter 2 arrays, 1 lista (y) y 1 array, (x), 1 lista (y) y 1 df.

#### Evaluate the performance:

In [ ]:
loss_and_metrics = model.evaluate(X_test, y_test, batch_size=128)

#### Predictions of new data:

In [ ]:
classes = model.predict(X_test, batch_size=128)

In [62]:
#### PRUEBA CODIGO:

In [69]:
from keras.layers import Dense, Activation
from keras.models import Sequential
model = Sequential([
    Dense(32, input_dim=2),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd')
model.fit([[0,1], [1,1], [1,0]], [1,2,3])

Epoch 1/10
3/3 [==============================] - 0s 131ms/step - loss: 2.5414
Epoch 2/10
3/3 [==============================] - 0s 618us/step - loss: 2.5268
Epoch 3/10
3/3 [==============================] - 0s 644us/step - loss: 2.5124
Epoch 4/10
3/3 [==============================] - 0s 650us/step - loss: 2.4981
Epoch 5/10
3/3 [==============================] - 0s 574us/step - loss: 2.4840
Epoch 6/10
3/3 [==============================] - 0s 728us/step - loss: 2.4701
Epoch 7/10
3/3 [==============================] - 0s 617us/step - loss: 2.4565
Epoch 8/10
3/3 [==============================] - 0s 600us/step - loss: 2.4433
Epoch 9/10
3/3 [==============================] - 0s 564us/step - loss: 2.4302
Epoch 10/10
3/3 [==============================] - 0s 760us/step - loss: 2.4173


In [64]:
### ESTO QUIERE DECIR QUE TENEMO BIEN INSTALADO KERAS Y TENSORFLOW. El problema esta en el codigo

In [128]:
# y_train = y_train.reshape((-1, 1)) 
# Solucion stack overflow

array([[0],
       [1],
       [1],
       ..., 
       [1],
       [1],
       [1]])